apiVersion: gateway.mulesoft.com/v1alpha1
kind: ApiInstance
metadata:
  name: config
spec:
  address: http://0.0.0.0:7080
  services:
    inventarios-ordenes:
      address: http://sps-inventory-svc:8080/inventory
      routes:
        - rules:
            - path: /inventarios(.*)
          config:
            destinationPath: /inventory
    regresos-inventarios:
      address: http://sps-order-inventory-svc:8080/inventory
      routes:
        - rules:
            - path: /egresoswuil/inventarios(.*)
          config:
            destinationPath: /inventory
    usuarios:
      address: http://sps-login-svc:8080/login
      routes:
        - rules:
            - path: /usuarios(.*)
          config:
            destinationPath: /login
    clientes:
      address: http://sps-login-svc:8080/clientes
      routes:
        - rules:
            - path: /clientes(.*)
          config:
            destinationPath: /clientes
  policies:
    - policyRef:
        name: jwt-validation-flex
      config:
        signingMethod: none
        signingKeyLength: 256
        textKey: MIIEwAIBADANBgkqhkiG9mpY+wL3FdkqIxXUCJX0tfKpCwBikKoQMzddt+ZmoZvjzIuFv9eploqBJhoL+HYOMzuWCshACn33TZGvx9SYs3aK+vm2cvFRQ6cw5zZJC2v12DNM41hblm7c/DK8BaTkPq54hSEu1jOlwH562g10vcivbvjoojL9VSwPAAzt2GupIrxTbEUIaVq7iKQ5O2/MOjCcAwcyt8TurUHpZlAMBCUGbFFCzIqWfkMiwq/rFq42wdGAEApy1TFkbwzhAkjHdLoC6CF3dFkLgJrkB7193wvyaU1gEKtCE5nt1LR/hq3hquUtxqO3AgMBAAECggEBANX6C+7EA/TADrbcCT7fMuNnMb5iGovPuiDCWc6bUIZCQ0yac45l7o1nZWzfzpOkIprJFNZoSgIF7NJmQeYTPCjAHwsSVraDYnn3Y4d1D3tM5XjJcpX2bs1NactxMTLOWUl0JnkGwtbWp1Qq+DBnMw6ghc09lKTbHQvhxSKNL/0UC+YmCYT5ODmxzLBwkzN5RhxQZNqol/4LYVdji9bS7N/UITw5E6LGDOo/hZHWqJsEfgrJTPsuCyrYlwrNkgmV2KpRrGz5MpcRM7XHgnqVym+HyD/r9E7MEFdTLEaiiHcmIsh1usJDEJMFIWkF+rnEoJkQHbqiKlQBcoqSbCmoMWECgYEA/4379mMPF0JJ/EER4VH7/ZYxjdyphenx2VYCWY/uzT0KbCWQF8KXckuoFrHAIP3EuFn6JNoIbja0NbhIHGrU29BZkATG8h/xjFy/zPBauxTQmM+yS2T37XtMoXNZNS/ubz2lJXMOapQQiXVRl/tzzpyWaCe9j0NT7DAU0ZFmDbECgYEA6ZbjkcOs2jwHsOwwfamFm4VpUspsYtED79vKzq5d7+Ii1kPKHj5fDnYkZd+mNwNZ02O6OGxh40EDML+i6nOABPg/FmXeVCya9Vump2Yqr2fAK3xm6QY5KxAjWWq2kVqmdRmICSL2Z9rBzpXmD5o06y9viOwd2bhBo0wB02416GecCgYEA+S/ZoEa3UFazDeXlKXBn5r2tVEb2hj24NdRINkzC7h23K/z0pDZ6tlhPbtGkJodMavZRk92GmvF8h2VJ62vAYxamPmhqFW5Qei12WL+FuSZywI7Fq/6oQkkYT9XKBrLWLGJPxlSKmiIGfgKHrUrjgXPutWEK1ccw7f10T2UXvgECgYEAnXqLa58G7o4gBUgGnQFnwOSdjn7jkoppFCClvp4/BtxrxA+uEsGXMKLYV75OQd6TIhkaFuxVrtiwj/APt2lRjRym9ALpqX3xkiGvz6ismR46xhQbPM0IXMc0dCeyrnZlQKkcrxucK/Lj1IBqy0kVhZB1IaSzVBqeAPrCza3AzqsCgYEAvSiEjDvGLIlqoSvKMHEVe8PBGOZYLcAdq4YiOIBgddoYyRsq5bzHtTQFgYQVK99Cnxo+PQAvzGb+dpjN/LIEAS2LuuWHGtOrZlwef8ZpCQgrtmp/phXfVi6llcZx4mMm7zYmGhh2AsA9yEQcacgc4kgDThAjD7VlXad9UHpNMO8=
        jwksServiceTimeToLive: 60
        jwksServiceConnectionTimeout: 10000
        validateAudClaim: false
        mandatoryAudClaim: false
        mandatoryNbfClaim: false
        mandatoryExpClaim: false
        validateCustomClaim: false
        mandatoryCustomClaims: []
        nonMandatoryCustomClaims: []
        skipClientIdValidation: true
      order: 2
    - policyRef:
        name: cors-flex
      config:
        publicResource: true
      order: 1  