# This is a basic workflow to help you get started with Actions

name: CI - demo mulesoft flex-gateway

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  validar-yaml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Validar YAML
        uses: GrantBirki/json-yaml-validate@v2.6.0
        with:
          files: "./config.yaml"
          comment: "true"

      - name: Mostrar contenido del archivo
        run: cat config.yaml 
      
      - name: Convertir a base 64
        run: 
          cat config.yaml | base64 > config.txt
      
      - name: Mostrar base 64
        run: cat config.txt
      
  Oc-openshift-Install:
    runs-on: ubuntu-latest
    needs: validar-yaml
    if: ${{ success()}}

    steps: 
      - name: Install oc openshift
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
      
  login:
    name: OpenShift Login and Test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Log in and set context
        # In a real workflow, point the 'uses' to a tag.
        # uses: redhat-actions/oc-login@v1
        uses: ./
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_username: ${{ secrets.TEST_USER }}
          openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
          #certificate_authority_data: ${{ secrets.CA_DATA }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Test
        run: |
          oc api-resources

      
      
          
        

   


        